### PR TITLE
Updated nim-smie.el and deleted old nim-indent.el

### PR DESCRIPTION
**Pull request by yuutayamada**
I updated nim-smie.el (applied forward declaration's indent and fixed some wrong indentation)
and completely deleted old nim-indent.el though I divided some convenience functions to other files.

### CODE REVIEW

**Comment by reactormonk** [comment]
Instead of just calling `indent-region`, could you have some code that is actually moved around? Just testing for identity isn't enough IMO.

**Comment by yuutayamada** [comment]
Almost tests start from unformatted state (except smie/raw directory's)
for example:
```nim
type
  Unit = object of Thing
    x: int
    y: int
  NewType* = object of RootEffect # check this line is dedented
```

is unformatted to

```nim
type
Unit = object of Thing
x: int
y: int
NewType* = object of RootEffect # check this line is dedented
```

and then do the `indent-region` and compare between original and 
formatted one.

I thought it's more easier to write test. (I mean making actual-xxx.nim and expected-xxx.nim.

**Comment by yuutayamada** [comment]
I added brief explanation about the test.

**Comment by reactormonk** [comment]
Sounds good to me. I missed the part where you kill the indentation.

**Pull request merged**
