### PR TITLE
Add character delimiter font lock

### PR DESCRIPTION
**Pull request by yuutayamada**
Hi, I added character-delimiter regex to highlight by font-lock.
Also, I deleted the "'" and "'''" from string delimiter's regex.

### CODE REVIEW

**Comment by reactormonk** [comment]
Do string blocks still work?

**Comment by yuutayamada** [comment]
The reason is if we used character as string-delimiter,  font-lock doesn't treat number type well.
(Sorry, I should have written this)

```nim
let
  y = 0'i8   # <- string face start here
  z = 0'i64 # <- and end here
```

**Comment by reactormonk** [comment]
I'll think of a way to test faces, then I'll come back to this PR.

**Comment by yuutayamada** [comment]
Thank you for your consideration:)

**Comment by reactormonk** [comment]
For testing: https://github.com/nim-lang/nim-mode/blob/master/tests/test-syntax.el - just add a sample to `tests/syntax/` and create a new test.

**Comment by yuutayamada** [comment]
I'm sorry. I would close this PR at once because I still found wrong highlight and 
I might take tame to fix that. As you wrote, I should have prepared more test.

**Comment by reactormonk** [comment]
If you feel like closing, you can do that yourself. But I'm glad the tests help with discovering bugs.

**Comment by yuutayamada** [comment]
Thanks.

**Pull request closed without merging**
