### PR TITLE
better instructions for beginners

### PR DESCRIPTION
**Pull request by krux02**

### CODE REVIEW

**Comment by yuutayamada** [comment]
> Currently only emacs 25 and higher is supported, if you try to install on latest stable release, you will run into [this problem](https://github.com/nim-lang/nim-mode/issues/100). 

I think this issue was solved. I also made sure 24.5.1 with `package-list-packages` and Emacs -Q (-Q is without any user configuration). Or is there another problem? (recently Emacs devel released Emacs 25 RC, so this issue may disappear anyway though)

**Comment by krux02** [comment]
I have emacs 24.5-4 on arch linux and I can ensure you, it does not work. It always complains about `internal--listify` to be not defined. last time I tried it, it didn't even work with `subr+` being installed.

**Comment by yuutayamada** [comment]
@krux02 could you modify README's PR? (On arch's emacs, nim-mode doesn't highlight) or maybe you should wait till arch's package manager use emacs25 because Emacs25's RC version was released recently.

**Comment by krux02** [comment]
what does it mean that the RC was released recently? How long do we need to wait for that version? Tomorrow I will test how well this version works on the linux machines at my university. They have Ubuntu LTS versions, but I don't know the version at the moment. It's not as new as the version I have on my arch linux.

**Comment by yuutayamada** [comment]
> what does it mean that the RC was released recently? How long do we need to wait for that version?

RC is Release Candidates. If the RC is no problem, emacs devel will release emacs 25.
But, sorry I don't know how long it take...

**Comment by krux02** [comment]
With the current development speed of emacs, and the general conservative nature of the emacs commutiny, I would guess it takes a year. And no I am not sarcastic that is truely what I think.

**Comment by krux02** [comment]
@yuutayamada Since you could reproduce the problem I had on Arch also on Ubuntu, I suggest I don't say it's an Arch specific problem. But I did add to the instructions, that you need a special branch of nimsuggest, because of what you suggested me to use in https://github.com/nim-lang/nim-mode/issues/134

**Comment by yuutayamada** [comment]
> I did add to the instructions, that you need a special branch of nimsuggest, ...

Thank you. I hoped the major-restructure branch merged soon, but it may take awhile...

**Comment by krux02** [comment]
So is there any reason left to not merge this pull request?

**Comment by yuutayamada** [comment]
Please modify about #100 if nim-mode's recent change fixed the highlight issue on arch.

**Comment by krux02** [comment]
what should I modify?

**Comment by yuutayamada** [comment]
I think you can delete the part of:

> An emacs major mode for the Nim programming language. Currently only emacs 25 and higher is supported, if you try to install on latest stable release, you will run into [this problem](https://github.com/nim-lang/nim-mode/issues/100). On arch linux you can install latest version of emacs with `yaourt emacs-git`, but be warned a complete build will need about 45 minutes (also depends on your hardware).

**Pull request merged**
