### PR TITLE
Add some automatic functions

### PR DESCRIPTION
**Pull request by yuutayamada**
(the term of electric means https://www.emacswiki.org/emacs/Electricity in Emacs)

1. backspace -> delete spaces by indent level if cursor is on beginning of start
2. space -> insert some spaces if cursor is on beginning of start
3. colon -> refactor and delete duplicate function

### CODE REVIEW

**Comment by reactormonk** [comment]
Is there a way to add tests for these functions?

**Comment by yuutayamada** [comment]
I felt difficult to make those functions' tests, though I checked manually.
I'm ok turning off those functions by default.

FYI, you can turn off those functions by following config:
```lisp
(add-to-list 'nim-mode-hook
               '(lambda () (electric-indent-mode -1)))
```

**Comment by reactormonk** [comment]
Nah, it's fine having them in, dependent on `electric-indent-mode`.

**Comment by yuutayamada** [comment]
Thank you for merging.

**Pull request merged**
