### PR TITLE
Eldoc: more information

### PR DESCRIPTION
**Pull request by yuutayamada**
applied some other information: var, let, const, macro, template.

One thing, I'm not sure is --v2 option. I could make sure company-mode and worked
normally, but if you have something worry about, please let me know

### CODE REVIEW

**Comment by yuutayamada** [comment]
Added some refinements:)

**Comment by yuutayamada** [comment]
I made a variable for nimsuggest's option, so now users can choose its
options. (I mean about --v2 option)

**Comment by reactormonk** [comment]
I would mention that `--epc` (and maybe even `--verbosity:0`) is required, or not even have it in the options. If you can change the options to a point where the whole thing breaks if you don't do something very specific, I don't think we should have it in there.

**Comment by yuutayamada** [comment]
Thanks. You are right. I moved those parameters.

**Pull request merged**
