### PR TITLE
Indent after colon

### PR DESCRIPTION
**Pull request by yuutayamada**
This PR enables indentation after ":". 
Originally, I thought supporting template's indentation, but it indents
other nim-mode's missing indentation. (like defer)

Please correct me if there are another usage of ":"
 (I'm still learning Nim)

### CODE REVIEW

**Comment by reactormonk** [comment]
You can use any identifier before a `:` with macros. E.g.

    dumpTree:
      foo:
        x = "bar"

is valid nim.

**Comment by yuutayamada** [comment]
Thanks. My implementation is just checking `:` at end of line, so in your macro example,
it indents second line and third line. Is it desired behavior?

**Comment by reactormonk** [comment]
I think we're talking about the same thing here, but just to be sure: the indentation should look like in my code sample. If it does indent after `:`, that's exactly correct.

**Comment by yuutayamada** [comment]
Thanks. I never use nim's macro yet and your explanation is really help.

**Comment by reactormonk** [comment]
Could you add my code sample to the PR?

**Comment by yuutayamada** [comment]
Sure. I added your macro sample to the test.
(But, when I tested it, my code didn't work well, so I changed my code little bit.)

**Comment by reactormonk** [comment]
Sweet, nice work.

**Pull request merged**
