### PR TITLE
Highlight and completion

### PR DESCRIPTION
**Pull request by yuutayamada**
- highlight more system.nim's functions
- highlight more nimscript.nim's functions
- auto-completion for system.nim's functions
- auto-completion for nimscript.nim's functions
- fixed some misconfigured highlight
- added nonoverloadable face for nonoverloadable
  functions (but use same color as builtin's)
- became non-casesensitive for highlighting

### CODE REVIEW

**Comment by reactormonk** [comment]
I don't exactly see the reasoning behind highlighting `system.nim` stuff, how about just tossing it? `system.nim` things aren't too different from e.g. nimble libraries.

**Comment by yuutayamada** [comment]
In NimScript files, currently I can't use flycheck though I'm not
sure there is correct way. So I wanted kind of visible marker in
NimScript files. (and I often forget correct spelling like
fileExist or fileExists)

Also the variables for system.nim and nimscript are used both highlight and
auto-completion, so if you change the variables, you might lose the ability
to correct auto-completion... (and I wouldn't maintain duplicated data for them)

**Comment by yuutayamada** [comment]
(ah, but I don't mind to remove highlighting code in this PR if it's too picky. My main purpose was auto-completion feature, and I can highlight by own customization)

**Comment by yuutayamada** [comment]
Thank you for merging

**Pull request merged**
