### PR TITLE
Implement indentation logic by python.el's way

### PR DESCRIPTION
**Pull request by yuutayamada**
Hi, I had a problem on the nim-mode about docstring, which it doesn't highlight correctly when the docstring is nested. (i.e, `"""foo"123"bar"""`)

So, I imported python.el functions. Along the way, I needed to split the nim-mode file to examine code and also many functions from python.el.
I wonder is this PR acceptable? Should I do something?
(I think actually putting all functions to nim-mode.el is really messy...)

FYI I also made sure that indentation problems, which we had recently.
the `for`, `case` & `of` statements were fixed by few codes in the python.el`s indentation functions.

### CODE REVIEW

**Comment by pigmej** [comment]
I think it's a way to go @yuutayamada, what do you @reactormonk think about it ?

My /new/ thing-at-point is also separated.

**Comment by reactormonk** [comment]
PR isn't merging correctly. Also, would you have some code samples for things it fixes so I can convert them to tests? Or just make the tests yourself.

**Comment by yuutayamada** [comment]
Sorry, I should have read the contributing.md.

But, I currently can not complete `cask install`...

```sh
-[15004](1)% cask install
Making version-control local to ctable-autoloads.el while let-bound!
Dependency epc failed to install: Wrong type argument: stringp, nil
Output:
Setting `package-selected-packages' temporarily since "emacs -q" would overwrite customizations
Setting `package-selected-packages' temporarily since "emacs -q" would overwrite customizations
Contacting host: stable.melpa.org:80
Generating autoloads for ctable.el...
Generating autoloads for ctable.el...done uta has logged on pts/2 from :0.     
```

Also, I got same error message on master branch.

> PR isn't merging correctly. Also, would you have some code samples for things it fixes so I can convert them to tests? Or just make the tests yourself.

I had been changed nim-indent-region to python's, but the indent function didn't work on your test(I mean 30-actual.nim).  So I changed it nim-mode's again and I could make sure via indent-region on my emacs.

**Comment by yuutayamada** [comment]
On completely indent broken code, both nim-mode's and python's can't handle the indent.

```nim
# crazy indents
case thing:
of "string":
  echo("foo")
        echo("wrong indent")
of 100:
  echo("number")
    echo("wrong indent")
  if true:
        echo("wrong indent")
      else:
    echo("foo")
      of nil:
            echo("foo")

# after indent by nim-mode's
case thing:
of "string":
  echo("foo")
  echo("wrong indent")
of 100:
  echo("number")
  echo("wrong indent")
  if true:
    echo("wrong indent")
else:
  echo("foo")
of nil:
  echo("foo")

# after indent by python's
case thing:
of "string":
  echo("foo")
  echo("wrong indent")
of 100:
  echo("number")
  echo("wrong indent")
  if true:
    echo("wrong indent")
      else:
        echo("foo")
      of nil:
        echo("foo")
```

Is this matter of flavor? But I prefer python's...

What do you think?

**Comment by reactormonk** [comment]
The else should align with the if imo. Don't use a second statement, because that's where auto indent may break because it actually has meaning.

**Comment by yuutayamada** [comment]
> The else should align with the if imo. Don't use a second statement, because that's where auto indent may break because it actually has meaning.

Sorry, the above `case` and `if` example's indentation was because of my commit (fixed at 5c07be4).

**Comment by yuutayamada** [comment]
Just for your information, this PR fixes #6 as well (I noticed now)

**Comment by yuutayamada** [comment]
Thank you for merging!

**Comment by reactormonk** [comment]
The example you provided in the commit doesn't work (see test) - it indents the comment to the first column instead of third.

**Comment by reactormonk** [comment]
1) Fix the test 2) Fix the code. Not sure which one is correct here.

**Pull request merged**
